export const CREATE_PLAYER = 'CREATE_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const EDIT_PLAYER = 'EDIT_PLAYER'
export const SHOW_HIDE_PLAYER_SKILLS = 'SHOW_HIDE_PLAYER_SKILLS'
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const SELECT_PLAYER = 'SELECT_PLAYER'
export const RESET_SELECTED_PLAYERS = 'RESET_SELECTED_PLAYERS';